# .github/workflows/build.yml

# 工作流名称
name: Build Github Control Workflow Go Binary

# 工作流触发器
on:
  # 允许手动在 Actions 页面触发
  workflow_dispatch:

jobs:
  build:
    name: Build arm64 Binary
    runs-on: macos-latest   # 用 macOS runner（支持 Darwin arm64）

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"   # 你项目用的 Go 版本

      - name: Install UPX
        run: brew install upx

      - name: Build arm64 binary
        working-directory: ./github-control-workflow
        run: |
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 \
          go build -ldflags="-s -w" -o githubwf

      - name: Compress with UPX
        working-directory: ./github-control-workflow
        run: upx --best --lzma githubwf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: githubwf-darwin-arm64

