# .github/workflows/build.yml

# 工作流名称
name: Build Github Control Workflow Go Binary

# 工作流触发器
on:
  # 允许手动在 Actions 页面触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest   # 使用 macOS runner (默认是 x86_64, 交叉编译 arm64)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary for Apple Silicon
        working-directory: ./github-control-workflow
        run: |
          GOOS=darwin GOARCH=arm64 go build -o githubwf .
          ls -lh githubwf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: githubwf-darwin-arm64
          path: ./github-control-workflow/githubwf

